-- MySQL Script generated by MySQL Workbench
-- Thu Nov 16 21:52:33 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema corujao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema corujao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `corujao` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `corujao` ;

-- -----------------------------------------------------
-- Table `corujao`.`Times`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `corujao`.`Times` (
  `idTime` INT NOT NULL AUTO_INCREMENT,
  `NomeTime` VARCHAR(45) NOT NULL,
  `LiderTime` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idTime`),
  UNIQUE INDEX `idTime_UNIQUE` (`idTime` ASC) VISIBLE,
  UNIQUE INDEX `NomeTime_UNIQUE` (`NomeTime` ASC) VISIBLE,
  UNIQUE INDEX `LiderTime_UNIQUE` (`LiderTime` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `corujao`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `corujao`.`Usuario` (
  `idUsu` INT NOT NULL AUTO_INCREMENT,
  `NomeUsu` VARCHAR(100) NOT NULL,
  `SenhaUsu` VARCHAR(45) NOT NULL,
  `EmailUsu` VARCHAR(150) NOT NULL,
  `Times_idTime` INT NOT NULL,
  PRIMARY KEY (`idUsu`),
  UNIQUE INDEX `idUsuário_UNIQUE` (`idUsu` ASC) VISIBLE,
  UNIQUE INDEX `NomeUsu_UNIQUE` (`NomeUsu` ASC) VISIBLE,
  UNIQUE INDEX `EmailUsu_UNIQUE` (`EmailUsu` ASC) VISIBLE,
  INDEX `fk_Usuário_Times1_idx` (`Times_idTime` ASC) VISIBLE,
  CONSTRAINT `fk_Usuário_Times1`
    FOREIGN KEY (`Times_idTime`)
    REFERENCES `corujao`.`Times` (`idTime`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `corujao`.`Pergunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `corujao`.`Pergunta` (
  `idPerg` INT NOT NULL AUTO_INCREMENT,
  `textoPerg` MEDIUMTEXT NOT NULL,
  `dificulPerg` VARCHAR(15) NOT NULL,
  `linguagemPerg` VARCHAR(20) NOT NULL,
  `repondidaPerg` TINYINT NOT NULL,
  PRIMARY KEY (`idPerg`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `corujao`.`Respostas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `corujao`.`Respostas` (
  `idRespostas` INT NOT NULL AUTO_INCREMENT,
  `textoResposta` LONGTEXT NOT NULL,
  `Pergunta_idPerg` INT NOT NULL,
  `Usuario_idUsu` INT NOT NULL,
  PRIMARY KEY (`idRespostas`),
  INDEX `fk_Respostas_Pergunta1_idx` (`Pergunta_idPerg` ASC) VISIBLE,
  INDEX `fk_Respostas_Usuario1_idx` (`Usuario_idUsu` ASC) VISIBLE,
  CONSTRAINT `fk_Respostas_Pergunta1`
    FOREIGN KEY (`Pergunta_idPerg`)
    REFERENCES `corujao`.`Pergunta` (`idPerg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Respostas_Usuario1`
    FOREIGN KEY (`Usuario_idUsu`)
    REFERENCES `corujao`.`Usuario` (`idUsu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `corujao`.`Comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `corujao`.`Comentario` (
  `idComentario` INT NOT NULL,
  `textoComentario` MEDIUMTEXT NOT NULL,
  `dateComentario` DATETIME NOT NULL,
  `Usuário_idUsu` INT NOT NULL,
  PRIMARY KEY (`idComentario`),
  UNIQUE INDEX `idComentario_UNIQUE` (`idComentario` ASC) VISIBLE,
  INDEX `fk_Comentario_Usuário1_idx` (`Usuário_idUsu` ASC) VISIBLE,
  CONSTRAINT `fk_Comentario_Usuário1`
    FOREIGN KEY (`Usuário_idUsu`)
    REFERENCES `corujao`.`Usuario` (`idUsu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `corujao`.`Usuario_has_Pergunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `corujao`.`Usuario_has_Pergunta` (
  `Usuário_idUsu` INT NOT NULL,
  `Pergunta_idPerg` INT NOT NULL,
  PRIMARY KEY (`Usuário_idUsu`, `Pergunta_idPerg`),
  INDEX `fk_Usuário_has_Pergunta_Pergunta1_idx` (`Pergunta_idPerg` ASC) VISIBLE,
  INDEX `fk_Usuário_has_Pergunta_Usuário1_idx` (`Usuário_idUsu` ASC) VISIBLE,
  CONSTRAINT `fk_Usuário_has_Pergunta_Usuário1`
    FOREIGN KEY (`Usuário_idUsu`)
    REFERENCES `corujao`.`Usuario` (`idUsu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuário_has_Pergunta_Pergunta1`
    FOREIGN KEY (`Pergunta_idPerg`)
    REFERENCES `corujao`.`Pergunta` (`idPerg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `corujao`.`inputsOutputs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `corujao`.`inputsOutputs` (
  `idInOut` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `inputs` VARCHAR(45) NOT NULL,
  `tipoInput` VARCHAR(45) NOT NULL,
  `outputs` VARCHAR(45) NOT NULL,
  `tipoOutpus` VARCHAR(45) NOT NULL,
  `Pergunta_idPerg` INT NOT NULL,
  PRIMARY KEY (`idInOut`),
  INDEX `fk_inputsOutputs_Pergunta1_idx` (`Pergunta_idPerg` ASC) VISIBLE,
  CONSTRAINT `fk_inputsOutputs_Pergunta1`
    FOREIGN KEY (`Pergunta_idPerg`)
    REFERENCES `corujao`.`Pergunta` (`idPerg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
